export default {
  //! Others
  TOGGLE_THEME: "TOGGLE_THEME",

  //! REFETCH
  REFETCH_HOUSE_LIST: "REFETCH_HOUSE_LIST",
  REFETCH_HOUST_DETAIL: "REFETCH_HOUST_DETAIL",
  REFETCH_ROOM_OVERVIEW: "REFETCH_ROOM_OVERVIEW",
  REFETCH_GUEST_DETAIL: "REFETCH_GUEST_DETAIL",

  //! OTHER
  DIALOG_OPEN: "DIALOG_OPEN",
  LOADING_APP: "LOADING_APP",
} as const;
