export default {
  //! REFETCH
  REFETCH_HOUSE_LIST: "REFETCH_HOUSE_LIST",
  REFETCH_HOUST_DETAIL: "REFETCH_HOUST_DETAIL",
  REFETCH_ROOM_OVERVIEW: "REFETCH_ROOM_OVERVIEW",
  REFETCH_GUEST_DETAIL: "REFETCH_GUEST_DETAIL",
  REFETCH_BILL_LIST: "REFETCH_BILL_LIST",
  REFETCH_GUEST_LIST: "REFETCH_GUEST_LIST",

  

  //! OTHER
  DIALOG_OPEN: "DIALOG_OPEN",
  LOADING_APP: "LOADING_APP",
  TOGGLE_THEME: "TOGGLE_THEME",
  IS_EDITING_INCOME_EXPENSE: "IS_EDITING_INCOME_EXPENSE",
  COLUMN_INCOME_EXPENSE: "COLUMN_INCOME_EXPENSE",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",

  //! DATA
  BILL_DETAIL: "BILL_DETAIL",

} as const;
